export const CONSTANT = {
  CHAT: {
    // 常量
    TITLE: "您好！我是灵眸洞察Agent，一个专为数据分析设计的智能助手",
    SEND_FILE_ID: "",
    BOT_NO: "BOT_NO",
    AGENT_NO: "AGENT_NO",
    AGENT_NAME: "AGENT_NAME",
    AGENT_VERSION_NO: "AGENT_VERSION_NO",
    SELECTED_SKILL: "SELECTED_SKILL",
    MODE: "MODE",
    REFRESH_RELEASE_STATUS: "REFRESH_RELEASE_STATUS",
    // 点击事件
    FUNCTION_CLICK: "FUNCTION_CLICK",
    FUNCTION_CLOSED: "FUNCTION_CLOSED",
    FUNCTION_ERROR: "FUNCTION_ERROR",
    FUNCTION_SUCCESS: "FUNCTION_SUCCESS",
    FUNCTION_LOADING: "FUNCTION_LOADING",
    FUNCTION_LOADING_END: "FUNCTION_LOADING_END",
    FUNCTION_LOADING_START: "FUNCTION_LOADING_START"
  }
}
